version: 2

builds:
  - skip: true

changelog:
  use: github
  abbrev: 7
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))?!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))?!?:.+$'
      order: 1
    - title: Other
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^ci:'
      - '^Merge pull request'
      - '^Merge branch'